const sportsPhrases = [
    "Super Bowl", "World Series", "Stanley Cup", "NBA Finals",
    "March Madness", "Kentucky Derby", "Indianapolis 500", "Daytona 500",
    "Tour de France", "Boston Marathon", "Wimbledon Finals", "US Open Tennis",
    "French Open", "Australian Open", "Masters Tournament", "British Open Golf",
    "PGA Championship", "Ryder Cup", "World Cup Soccer", "Champions League",
    "Premier League", "La Liga", "Serie A", "Bundesliga",
    "MLS Cup", "Copa America", "Euro Championship", "Winter Olympics",
    "Summer Olympics", "Paralympic Games", "X Games", "Extreme Sports",
    "Home Run", "Grand Slam", "Triple Crown", "Perfect Game",
    "No Hitter", "Batting Average", "Touchdown Pass", "Field Goal",
    "Two Point Conversion", "Hail Mary", "Quarterback Sack", "Running Back",
    "Wide Receiver", "Tight End", "Slam Dunk", "Three Pointer",
    "Free Throw", "Alley Oop", "Fast Break", "Pick and Roll",
    "Buzzer Beater", "Hat Trick", "Power Play", "Penalty Kill",
    "Face Off", "Slap Shot", "Body Check", "Penalty Kick",
    "Corner Kick", "Free Kick", "Yellow Card", "Red Card",
    "Bicycle Kick", "Header Goal", "Penalty Shootout", "Ace Serve",
    "Double Fault", "Match Point", "Break Point", "Tiebreaker",
    "Deuce", "Hole in One", "Eagle Putt", "Birdie Putt",
    "Bogey", "Par Score", "Fairway Shot", "Sand Trap",
    "Putting Green", "Knockout Punch", "Technical Knockout", "Championship Belt",
    "Title Fight", "Checkmate", "Stalemate", "Chess Grandmaster",
    "Poker Face", "Royal Flush", "Full House", "Texas Hold Em",
    "All In", "Monopoly Board", "Scrabble Tiles", "Trivial Pursuit",
    "Dungeons and Dragons", "Video Game", "Console Gaming", "Esports Tournament",
    "High Score", "Level Up", "Boss Battle", "Game Over",
    "Power Up", "Battle Royale", "First Person Shooter", "Figure Skating",
    "Ice Dancing", "Hockey Rink", "Curling Stone", "Bobsled Run",
    "Ski Jump", "Downhill Skiing", "Slalom Course", "Snowboard Halfpipe",
    "Big Air", "Mountain Biking", "Road Cycling", "BMX Racing",
    "Triathlon Race", "Ironman Competition", "Long Jump", "High Jump",
    "Triple Jump", "Pole Vault", "Shot Put", "Discus Throw",
    "Javelin Throw", "Sprint Race", "Relay Race", "Hurdle Race",
    "Marathon Running", "Rock Climbing", "Surfing Competition", "Big Wave",
    "Scuba Diving", "Sailing Race", "Americas Cup", "Rowing Race",
    "Kayak Race", "Archery Target", "Bullseye Shot", "Fencing Match",
    "Balance Beam", "Uneven Bars", "Vault Jump", "Pommel Horse",
    "Trampoline Jump", "Weightlifting", "Powerlifting", "Bench Press",
    "Wrestling Match", "Sumo Wrestling", "Judo Match", "Taekwondo",
    "Mixed Martial Arts"
];
