const worldPhrases = [
    "Eiffel Tower", "Great Wall of China", "Amazon Rainforest", "Mount Everest",
    "Sahara Desert", "Grand Canyon", "Niagara Falls", "Big Ben",
    "Statue of Liberty", "Taj Mahal", "Machu Picchu", "Colosseum",
    "Sydney Opera House", "Golden Gate Bridge", "Stonehenge", "Pyramids of Giza",
    "Great Barrier Reef", "Victoria Falls", "Northern Lights", "Dead Sea",
    "Mount Fuji", "Venice Canals", "Swiss Alps", "Mona Lisa",
    "Hollywood Sign", "Times Square", "Las Vegas Strip", "Central Park",
    "Buckingham Palace", "Leaning Tower of Pisa", "Christ the Redeemer",
    "Easter Island", "Angel Falls", "Galapagos Islands", "Antarctica",
    "African Safari", "Tokyo Skyline", "Paris Fashion", "Brazilian Carnival",
    "Mediterranean Sea", "Pacific Ocean", "Atlantic Ocean", "Indian Ocean",
    "North Pole", "South Pole", "Equator Line", "International Date Line",
    "Time Zone", "World Map", "Globe Trotting", "Jet Lag",
    "Passport Control", "Border Crossing", "Currency Exchange", "Foreign Language",
    "World Heritage Site", "National Park", "Capital City", "Island Nation",
    "Mountain Range", "River Delta", "Tropical Beach", "Volcanic Eruption",
    "Earthquake Zone", "Hurricane Season", "Monsoon Rains", "Desert Oasis",
    "Coral Reef", "Rainforest Canopy", "Arctic Tundra", "Bamboo Forest",
    "Rice Paddy", "Tea Plantation", "Coffee Beans", "Silk Road",
    "Spice Trade", "World Cuisine", "Street Food", "Local Market",
    "Ancient Ruins", "Medieval Castle", "Modern Skyline", "Underground City",
    "Floating Market", "Night Market", "Temple Complex", "Sacred Mountain",
    "Holy City", "Pilgrimage Route", "Cultural Festival", "Traditional Dance",
    "Folk Music", "Native Tribe", "Indigenous People", "Colonial History",
    "Independence Day", "National Anthem", "World Cup", "Olympic Games",
    "World Record", "Seven Wonders", "Lost City", "Hidden Paradise",
    "Remote Island", "Uncharted Territory", "Expedition Team", "World Explorer",
    "Bermuda Triangle", "Great Sphinx", "Panama Canal", "Suez Canal",
    "Mount Kilimanjaro", "Amazon River", "Nile River", "Mississippi River",
    "Danube River", "Rhine River", "Ganges River", "Yangtze River",
    "Himalayan Mountains", "Rocky Mountains", "Andes Mountains", "Atlas Mountains",
    "Appalachian Trail", "Great Plains", "Australian Outback", "Gobi Desert",
    "Atacama Desert", "Mojave Desert", "Arabian Desert", "Caribbean Islands",
    "Hawaiian Islands", "Greek Islands", "New Zealand", "Madagascar",
    "Iceland", "Greenland", "Bora Bora", "Maldives",
    "Seychelles", "Fiji Islands", "Hong Kong Harbor", "Singapore Skyline",
    "Dubai Skyscrapers", "Shanghai Tower", "Kremlin Palace", "Vatican City",
    "Forbidden City", "Angkor Wat", "Petra Jordan", "Chichen Itza",
    "Acropolis Athens", "Roman Forum", "Pompeii Ruins", "Bay of Bengal",
    "Gulf of Mexico", "Persian Gulf", "Red Sea", "Black Sea",
    "Caspian Sea", "Baltic Sea", "English Channel", "Mount Vesuvius",
    "Ring of Fire", "Mariana Trench", "Great Rift Valley", "Yosemite Valley",
    "Yellowstone Geyser", "Norwegian Fjords", "Scottish Highlands", "French Riviera",
    "Amalfi Coast", "Lake Como", "Lake Geneva", "Crater Lake",
    "Great Lakes", "Lake Victoria", "Serengeti Plains", "Masai Mara",
    "Okavango Delta", "Congo Rainforest", "Borneo Jungle", "Patagonia Region",
    "Iguazu Falls", "Edinburgh Castle", "Windsor Castle", "Neuschwanstein Castle",
    "Versailles Palace", "Red Square Moscow", "Tiananmen Square", "Trafalgar Square",
    "Brandenburg Gate", "Arc de Triomphe", "Fifth Avenue", "Wall Street",
    "Shibuya Crossing", "Burj Khalifa", "Route Sixty Six", "Pacific Coast Highway",
    "Trans Siberian Railway", "Orient Express", "Camino de Santiago"
];
