const sciencePhrases = [
    "Artificial Intelligence", "Machine Learning", "Neural Network", "Deep Learning",
    "Computer Vision", "Robotics", "Automation", "Self Driving Car",
    "Electric Vehicle", "Battery Technology", "Solar Panel", "Wind Turbine",
    "Nuclear Power", "Renewable Energy", "Carbon Footprint", "Climate Change",
    "Global Warming", "Greenhouse Effect", "Ozone Layer", "Fossil Fuel",
    "Genetic Engineering", "Gene Therapy", "CRISPR Technology", "DNA Sequence",
    "Human Genome", "Stem Cell", "Cloning", "Biotechnology",
    "Drug Discovery", "Clinical Trial", "Vaccine Development", "Antibody",
    "Immune System", "Virus Mutation", "Space Exploration", "Mars Mission",
    "Moon Landing", "Space Station", "Satellite Orbit", "Rocket Launch",
    "Space Shuttle", "Black Hole", "Supernova", "Galaxy Formation",
    "Dark Matter", "Dark Energy", "Big Bang", "Gravitational Wave",
    "Hubble Space", "James Webb", "Quantum Computing", "Quantum Mechanics",
    "Particle Physics", "Higgs Boson", "Antimatter", "String Theory",
    "Theory of Relativity", "Speed of Light", "Time Dilation", "Wormhole",
    "Parallel Universe", "Periodic Table", "Chemical Element", "Atomic Number",
    "Chemical Bond", "Organic Chemistry", "Biochemistry", "Protein Folding",
    "Enzyme Reaction", "Chemical Reaction", "Nuclear Fusion", "Nuclear Fission",
    "Radioactive Decay", "Computer Processor", "Graphics Card", "Memory Chip",
    "Hard Drive", "Cloud Computing", "Data Center", "World Wide Web",
    "Search Engine", "Social Media", "Virtual Reality", "Augmented Reality",
    "Three D Printing", "Nanotechnology", "Microchip", "Semiconductor",
    "Fiber Optic", "Wireless Network", "Five G Technology", "Bluetooth",
    "GPS Navigation", "Cybersecurity", "Firewall", "Computer Virus",
    "Data Breach", "Facial Recognition", "Fingerprint Scanner", "Voice Recognition",
    "Touch Screen", "Smartphone", "Tablet Computer", "Smart Watch",
    "Smart Home", "Internet of Things", "Voice Assistant", "Electric Motor",
    "Photosynthesis", "Mitochondria", "Cell Division", "Chromosome",
    "Genetic Code", "Evolution Theory", "Natural Selection", "Ecosystem",
    "Biodiversity", "Food Chain", "Endangered Species", "Marine Biology",
    "Coral Bleaching", "Plate Tectonics", "Continental Drift", "Earthquake Fault",
    "Volcanic Activity", "Richter Scale", "Tsunami", "Fossil Record",
    "Ice Age", "Carbon Dating", "Dinosaur Fossil", "Weather Pattern",
    "Jet Stream", "Doppler Radar", "Hurricane Category", "Tornado Warning",
    "Water Cycle", "Scientific Method", "Hypothesis Testing", "Peer Review",
    "Laboratory Experiment"
];
